VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "GameState"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function State() As GameState
End Function

Public Sub Update(Time As Long)
End Sub

Public Sub Draw()
End Sub

Public Sub Listen(GameEvent As DomainEvent)
End Sub

Public Sub Init(Render As RenderingEngine)
End Sub


